#pragma once

// In deployment, rust types are already defined by the generated header
// In development, we need to include rust/cxx.h
#ifndef CXXBRIDGE1_RUST_STR
#include "rust/cxx.h"
#endif

#include <memory>
#include <string>

// Forward declare the MessageKind enum that will be generated by cxx
enum class MessageKind : uint8_t;

class CppStatusBackend {
public:
    // Pure virtual functions make this class abstract
    virtual void report(MessageKind kind, rust::Str message) = 0;
    virtual void dump_error_logs(rust::Slice<const uint8_t> output) = 0;
    // Add a virtual destructor for proper cleanup of derived classes
    virtual ~CppStatusBackend() = default;
};
