name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo cinstall --prefix=./dist --library-type=staticlib
    - name: Upload artifact
      uses: actions/download-artifact@v4.3.0
      with:
        name: Ubuntu-Library
        path: dist
